# name: Update with Upstream

# on:
#   schedule:
#     - cron: '0 0 * * 0'  # Runs once a week, on Sunday at midnight
#   workflow_dispatch:  # Allows manual triggering

# jobs:
#   update-repo:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Git
#         run: |
#           git config --global user.name 'github-actions[bot]'
#           git config --global user.email 'github-actions[bot]@users.noreply.github.com'

#       - name: Fetch upstream changes
#         run: |
#           git remote add upstream https://github.com/steven-tey/precedent
#           git fetch upstream
#           git checkout main
#           git merge upstream/main --allow-unrelated-histories

#       - name: Push changes
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           git push origin main
